config/routes.rb
Rails.application.routes.draw do
  get 'groups', to: 'groups#index'
  root 'groups#index'

  get 'groups/new'
  post 'groups', to: 'groups#create'
  
  get 'groups/:id', to: 'groups#show', as: 'group'

  get 'groups/:id/edit', to: 'groups#edit', as: 'group_edit'
  patch 'groups/:id', to: 'groups#update'
  
  delete 'groups/:id', to: 'groups#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  enum group_type: %w[GirlGroup BoyGroup Banda Solista]
  enum style: %w[k-pop j-pop c-pop rock country jazz blues chayanne]
  enum status: %w[Activo Descansando Disuelto Inactivo]

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]
  before_action :set_selects, only: %i[new edit create update]

  def index
    @q = Group.ransack(params[:q])
    @groups = @q.result(distinct: true)
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.create(group_params)
    respond_to do |format|
      if @group.save
        format.html {redirect_to @group, notice: "Se re creo el grupo"}
      else
        format.html {render :new}
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html {redirect_to @group, notice: 'Ahre que lo cambiaste'}
      else
        format.html {render :edit}
      end
    end
  end

  def show
  end

  def destroy
    @group.destroy
    redirect_to root_path, notice: 'Igual era mejor que la G46'
  end
  

  private
  
  def set_group
    @group = Group.find(params[:id])
  end
  
  def set_selects
    @types = Group.group_types.keys.to_a
    @styles = Group.styles.keys.to_a
    @statuses = Group.statuses.keys.to_a
  end

  def group_params
    params.require(:group).permit(:name, :crew, :group_type, :style, :status) 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group, local: true) do |f| %>
  <% if group.errors.any? %>
    <div id = 'error_explanation'>
      <h2>Este Grupo no se pudo crear por las siguientes razones</h2>
      <ul>
        <% group.errors.full_messages.each do |msg|%>
          <li><%= msg %></li>
          <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :name, "Nombre" %>
    <%= f.text_field :name, placeholder: "el re nombre", class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :crew, "Integrantes" %>
    <%= f.number_field :crew, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :group_type, "Tipo" %>
    <%= f.select :group_type, options_for_select(@types),{:include_blank => true}, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :style, "Estilo" %>
    <%= f.select :style, options_for_select(@styles),{:include_blank => true}, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :status, "En que anda" %>
    <%= f.select :status, options_for_select(@statuses),{:include_blank => true}, class: 'form-control' %>
  </div>

  <div class = 'actions'>
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<div class="container">
  <%= render 'form', group: @group %>
</div>

app/views/groups/index.html.erb
<%= render 'shared/navbar' %>


<p id="notice"><%= notice %></p>

<div class="container">
  <table class="table">
    <thead>
      <tr>
        <th>Nombre</th>
        <th><%= sort_link(@q, :crew, 'Integrantes') %></th>
        <th>Tipo</th>
        <th>Estilo</th>
        <th>Status</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @groups.each do |group| %>
        <tr> 
          <td><%= group.name %></td>
          <td><%= group.crew %></td>
          <td><%= group.group_type %></td>
          <td><%= group.style %></td>
          <td><%= group.status %></td>
          <td><%= link_to group do %>
                <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-eye" width="32" height="32" viewBox="0 0 24 24" stroke-width="2" stroke="#00b341" fill="none" stroke-linecap="round" stroke-linejoin="round">
                  <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                  <circle cx="12" cy="12" r="2" />
                  <path d="M22 12c-2.667 4.667 -6 7 -10 7s-7.333 -2.333 -10 -7c2.667 -4.667 6 -7 10 -7s7.333 2.333 10 7" />
                </svg>
              <% end %>
          </td>
          <td><%= link_to group_edit_path(group.id) do %>
                <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-edit" width="32" height="32" viewBox="0 0 24 24" stroke-width="2" stroke="#00b341" fill="none" stroke-linecap="round" stroke-linejoin="round">
                  <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                  <path d="M9 7h-3a2 2 0 0 0 -2 2v9a2 2 0 0 0 2 2h9a2 2 0 0 0 2 -2v-3" />
                  <path d="M9 15h3l8.5 -8.5a1.5 1.5 0 0 0 -3 -3l-8.5 8.5v3" />
                  <line x1="16" y1="5" x2="19" y2="8" />
                </svg>
              <% end %>
          </td>
          <td><%= link_to group, method: :delete, data: {confirm: 'Seguro?'}  do %>
                <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-eraser" width="32" height="32" viewBox="0 0 24 24" stroke-width="2" stroke="#ff4500" fill="none" stroke-linecap="round" stroke-linejoin="round">
                  <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                  <path d="M19 19h-11l-4 -4a1 1 0 0 1 0 -1.41l10 -10a1 1 0 0 1 1.41 0l5 5a1 1 0 0 1 0 1.41l-9 9" />
                  <line x1="18" y1="12.3" x2="11.7" y2="6" />
                </svg>
              <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'Crear nuevo Grupo', groups_new_path, class: 'btn btn-success' %>
</div>

app/views/groups/new.html.erb
<div class="container">
  <%= render 'form', group: @group %>
</div>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @group.name %>
</p>

<p>
  <strong>Integrantes</strong>
  <%= @group.crew %>
</p>

<p>
  <strong>Estilo</strong>
  <%= @group.style %>
</p>

<p>
  <strong>En que anda</strong>
  <%= @group.status %>
</p>

<p>
  <strong>Tipo de Grupo:</strong>
  <%= @group.group_type %>
</p>

<%= link_to 'Ir al root', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crood</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container pt-5">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand">Grupos</a>
  <%= search_form_for @q do |f|%>
    <div class="form-group form-inline my-2 my-lg-0">
      <%= f.select :status_eq, options_for_select(Group.statuses, @q.status_eq), {}, {class: 'form-control mx-2'} %>
      <%= f.submit 'Filtrar', class: 'btn btn-primary' %>
    </div>
  <% end %>
</nav>